[project]
name = "nvim"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
requires-python = ">=3.13"
dependencies = [
    "neovim>=0.3.1",
    "pip>=25.0.1",
    "pynvim>=0.5.2",
]
